version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ny_taxi_pg
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./sql:/sql

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: taxi_python
    volumes:
      - ./data:/app/data
